package com.isoft.test;
// Generated 2016-4-16 10:51:23 by Hibernate Tools 3.5.0.Final

/**
 * TSysUser generated by hbm2java
 */
public class TSysUser implements java.io.Serializable {

	private String TUserId;
	private String TUserName;
	private String TUserPwd;
	private String TGender;

	public TSysUser() {
	}

	public TSysUser(String TUserId) {
		this.TUserId = TUserId;
	}

	public TSysUser(String TUserId, String TUserName, String TUserPwd, String TGender) {
		this.TUserId = TUserId;
		this.TUserName = TUserName;
		this.TUserPwd = TUserPwd;
		this.TGender = TGender;
	}

	public String getTUserId() {
		return this.TUserId;
	}

	public void setTUserId(String TUserId) {
		this.TUserId = TUserId;
	}

	public String getTUserName() {
		return this.TUserName;
	}

	public void setTUserName(String TUserName) {
		this.TUserName = TUserName;
	}

	public String getTUserPwd() {
		return this.TUserPwd;
	}

	public void setTUserPwd(String TUserPwd) {
		this.TUserPwd = TUserPwd;
	}

	public String getTGender() {
		return this.TGender;
	}

	public void setTGender(String TGender) {
		this.TGender = TGender;
	}

}
